### ISSUE TITLE
objcopy: section below image base

### ISSUE THREAD

**Issue by benthetechguy** [andreyv/sbupdate#63] opened 2023-08-02 02:02 UTC
When I upgrade my kernel, I get this warning while it generates the unified kernel image:

```
Generating and signing linux-signed.efi
objcopy: /efi/EFI/Linux/linux-signed.efi:.osrel: section below image base
objcopy: /efi/EFI/Linux/linux-signed.efi:.cmdline: section below image base
objcopy: /efi/EFI/Linux/linux-signed.efi:.linux: section below image base
objcopy: /efi/EFI/Linux/linux-signed.efi:.initrd: section below image base
Signing Unsigned original image
```

The UEFI fails to boot to the image.

**Comment by Maryse47** [comment] 2023-08-02 10:50
Duplicate of https://github.com/andreyv/sbupdate/issues/56

**Closed** 2023-08-02 18:14 UTC

**Comment by benthetechguy** [comment] 2023-08-02 18:30
Sorry, I didn't see that since it was closed before the issue was solved.
