### ISSUE TITLE
[Feature Request] Please add an option to sign already created image

### ISSUE THREAD

**Issue by Shished** [andreyv/sbupdate#54] opened 2022-05-13 10:57 UTC
`mkinitcpio` and `dracut` can create Unified kernel images without 3rd party tools
https://wiki.archlinux.org/title/Unified_kernel_image#Preparing_a_unified_kernel_image
This tool does the same which is redundant. 
Can you add an option to bypass the creation of the image and just sign the created file which is located in a specified path?

**Comment by andreyv** [comment] 2022-05-13 19:13
Duplicate of #45

**Closed by andreyv** 2022-05-13 19:13 UTC
